### ISSUE TITLE
Matlab -> loadNN

### ISSUE THREAD

**Issue by alduxvm** [yabata/pyrenn#1]
Hi!

First of all, great work! its amazing and the documentation is great!

I'm trying to load a NN, previously saved using: `saveNN(netBFGS,filename)`... 

But when trying to load it and perform more experiments, I do: `net = loadNN('Nets/netLM');`, and I'm getting this errors:

```
Error using xlsread (line 128)
XLSREAD unable to open file 'Nets/netLM'.
File 'Nets/netLM' not found.
Error in loadNN (line 10)
    [~,~,rawData] = xlsread(filename);
```

After checking if my file exists (which it does...) I tried to imported like on loadNN.m using: `[~,~,Data] = xlsread('Nets/netLM')` and I'm getting:

```
Error using xlsread (line 247)
Unable to read XLS file /Nets/netLM. File is not in recognized format.
```

Is there might be a problem with saveNN?? maybe being saved not in the proper format? or maybe on MATLAB_R2015a the xlsread function is changed and not compatible with the CSV format?

**Comment by yabata** [comment]
Hi,

thank you :)

I just tested it with MATLAB_R2015b and I don't get any error.

Try to use '*.cvs' when saving and loading the file:

```
saveNN(net,'name.csv')

net = loadNN('name.csv')
```

Here is my example:
[pyrenn_save_load.zip](https://github.com/yabata/pyrenn/files/131092/pyrenn_save_load.zip)

**Comment by alduxvm** [comment]
something is wrong here!!!

I was executing your script and this happened:

<img width="1231" alt="screen shot 2016-02-15 at 21 03 56" src="https://cloud.githubusercontent.com/assets/8823379/13060208/bb048f32-d427-11e5-8cf8-f077267aa26d.png">

What do you think is the issue?

**Comment by yabata** [comment]
Seems like xlsread does not read csv files properly when you are not using Windows with a MS Excel installation, as NKN writes [here](http://stackoverflow.com/questions/13579306/error-using-xlsread-command-in-matlab)

I changed the loadNN function so that xlsread is not used any more. Let me know if it works for you.

**Comment by alduxvm** [comment]
That did it! now is working great!!

Thanks a lot!
